name: dev_bapsfda
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.*
  - pip
  - mamba
  - poetry>=1.6
  - pytest
  - black>=23.1
  - mypy
platforms:
  - linux-64
  - osx-64
  - win-64
  - osx-arm64  # For Apple Silicon, e.g. M1/M2
  - linux-aarch64  # aka arm64, use for Docker on Apple Silicon
  - linux-ppc64le